#1 Frontend
fletcher97/transcendence pull request #3
Opened 2023-12-15 16:56 UTC by davidbekic

I'm opening this PR so I can start testing the endpoints in the Django backend from my frontend.

**Changes**:
- Added basic frontend with mockup login and dashboard pages
- Changed nginx.conf to serve front files
- Added Makefile that runs docker compose files
- Added front service to compose-file

Atm there's no shared volume between nginx and front services, nginx simply serves the front directory directly from local machine. This is for faster development purposes, i.e. if I make a change in front, I don't need to rerun containers. I don't know if this causes any problems or if we even need to change this in the future.

2023-12-18 14:13 UTC, fletcher97 requested changes
As much as possible try to keep the code in master as clean as possible. Do keep any commented code around. If you need you can keep it in your branch but remove it for the merge.

2023-12-18 14:13 UTC, fletcher97 commented on nginx/nginx.conf
You need to be able to communicate with the backend. The changes you made make it unaccessable. You should add a new upstream and server entries for the front and possibly changed the back to use a different port. Both to test and use the back for other things (like the cli app) we require it to be accessible

2023-12-18 14:13 UTC, fletcher97 commented on nginx/Dockerfile
The changes here are not required I don't think. By default (since we pull an nginx image) it should all be ready to go. Also there shouldn't be any need to expose the port as compose would handle it

2023-12-18 16:19 UTC, davidbekic commented on nginx/nginx.conf
Thanks. Completely forgot that backend should be exposed outside our app too. 

I'm afraid my complete lack of skills for nginx have been exposed. Do you reckon a new nginx.conf like this would work?
``` 
upstream backend {
  server back:8000;
}

server {
  listen 443 ssl;

  ssl_certificate /etc/nginx/ssl/transcendence.crt;
  ssl_certificate_key /etc/nginx/ssl/transcendence.key;
  ssl_protocols TLSv1.2 TLSv1.3;

  error_page 497 =301 https://$host:$server_port$request_uri;

  location /api/ {
    proxy_pass http://backend;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_redirect off;
  }

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }
}
```

So here both frontend and backend share the same server block and all backend endpoints are accessed through "domain.com/api/", and actual website through "domain.com"(I only know this works with certainty for frontend since there aren't any backend endpoints yet).

Is there any reason to have two separate server blocks? And are we happy using "domain.com/api" or do we prefer "api.domain.com"? If so I believe we would need 2 server blocks. Also, do you think an upstream for frontend is necessary, considering it's served from "/usr/share/nginx/html"? Or do you think there's a better way to serve the frontend files? 

Regarding the backend port, I don't understand completely; do you mean it should have another port than 8000?

Again, excuse my nginx ignorance. If this file looks completely wrong please feel free to provide a completely new nginx.conf.

2023-12-18 16:20 UTC, davidbekic commented on nginx/Dockerfile
Removed the two lines and it works, thanks

2023-12-18 16:59 UTC, davidbekic commented
Are we happy with the Makefile for now? Should I remove the `docker system prune -af` line and replace it with something? Or just have it run `docker compose down`?

2023-12-18 19:01 UTC, IsraelR1099 requested changes
What i have instead of docker system prune -af, is this:
remove-images:
        @echo "$(RED)Removing images...$(RESET)"
        @docker rmi -f $$(docker images -q)

remove-containers:
        @echo "$(RED)Removing containers...$(RESET)"
        @docker container prune -f

remove-all: remove-containers remove-images
        @echo "$(RED)Removing all...$(RESET)"
        
So that i just remove the images and containers, no the volumes.

2023-12-19 10:22 UTC, fletcher97 commented on nginx/nginx.conf
The proposed file looks fine. If you had a container with the fronted that required access from the nginx server then you'd need a 8000's port (or something else. Up2You). However if you mount the front as a volume on the nginx docker there is no longer a need to create separate entries.

For the back endpoint I have no complaints about domain.com/api/...

2023-12-22 12:07 UTC, fletcher97 approved these changes

2023-12-22 16:33 UTC, IsraelR1099 approved these changes
Everything is okay for me now

2023-12-22 16:48 UTC, merged