Adding volume for backend
fletcher97/transcendence pull request #6
Opened 2023-12-17 17:12 UTC by IsraelR1099

I have just added the volumen for the backend, so that we have it on the master branch. There is some new Env variables that i will need for creating the superuser of django.

2023-12-18 11:00 UTC, fletcher97 requested changes
Update env.sample

2023-12-18 11:00 UTC, fletcher97 commented on compose.yaml
If you add env vars please change the env.sample

2023-12-18 16:28 UTC, davidbekic approved these changes

2023-12-18 16:30 UTC, davidbekic submitted a review, later dismissed

2023-12-27 11:26 UTC, fletcher97 commented
There are currently no changes and thus this PR is useless. I'm closing it. If you want, add changes and reopen the PR

2023-12-27 11:26 UTC, closed without merging