Pong
fletcher97/transcendence pull request #9
Opened 2024-01-30 18:44 UTC by fletcher97

Added a base for pong [WIP]
Changed django setting to work in debug mode
Added websocket setup
Added a working nginx conf

2024-01-30 19:56 UTC, IsraelR1099 commented on compose.yaml
Notice that :z and :Z flags labels do not work on systems that do not have SELinux, and on docker official documentation they say that those labels are ignored on services. If we keep using MacOs then these labels have no relevance

2024-01-30 19:56 UTC, IsraelR1099 commented on back/src/pong/admin.py
As we do not use admin app this file could be removed

2024-01-31 11:02 UTC, davidbekic approved these changes

2024-01-31 11:55 UTC, davidbekic requested changes
In compose file: nginx service still depends on front service we removed

2024-02-02 14:39 UTC, fletcher97 commented on compose.yaml
As we'll be using a vm this should be a problem, Plus it's mainly for front dev and not necessary for prod

2024-02-02 14:47 UTC, fletcher97 commented on back/src/pong/admin.py
Admin has been removed

2024-02-02 14:48 UTC, davidbekic approved these changes

2024-02-02 14:51 UTC, IsraelR1099 approved these changes
it looks good for me

2024-02-02 14:52 UTC, merged